name: Debut
author: FuséeNoire
description: Début is a small teleport manager for Spigot servers.
website: https://oko.moe
version: 0.1.0
main: moe.oko.debut.Debut
api-version: 1.17
commands:
  otp:
    description: When first joining the server, you have an optional one time teleport.
    usage: /<command> [request|accept] player
    aliases: []