name: Debut
author: FuséeNoire
description: Début is a small teleport manager for Spigot servers.
website: https://oko.moe
version: 0.1.0
main: moe.oko.debut.Debut
api-version: 1.17
commands:
  otp:
    description: A one time teleport command.
    usage: /<command> [request|accept] player
    aliases: []
  debut:
    description: Debug command
    usage: /<command> [list|add|remove] player
    aliases: []

